name: Production sync

on:
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  sync:
    name: sync-orgs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set GitHub token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token

      - name: Sync GitHub orgs
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.3@sha256:03b7dc21ec9a18ded7d73175b5920e815cb672fe03e56dbd8ef2a3dc2595ff91
        with:
          github-token-path: ./token
          config-path: orgs
          min-admins: 3
          required-admins: "auggie-bot,cpanato,justaugustus"
          fix-org: true
          fix-org-members: true
          fix-teams: true
          fix-team-members: true
          fix-team-repos: true
          confirm: true
